version: "2.2"
services:
  mysql:
    image: mariadb:latest
    environment:
      - "MYSQL_ROOT_PASSWORD=asdfasdfasdf"
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/
  app:
    build: src/
    restart: always
    ports:
      - 5000:5000
    environment:
      - "DB_HOST=mysql"
      - "DB_USER=root"
      - "DB_PASSWORD=asdfasdfasdf"
